#!/bin/sh
docker buildx create --use
docker buildx build \
  --progress=plain \
  --platform="linux/amd64,linux/arm64" \
  --tag $IMAGE_NAME
   .
#,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6
